version: "3"

services:
  app:
    user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: dev_skymix
    container_name: dev_skymix
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./src:/home/worker
    ports:
      - 3000:3000